=== mydung1308/CongNgheXML/student_unique.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->


<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="school">
    <xs:complexType>
      <xs:sequence>
        <!-- Danh sách sinh viên -->
        <xs:element name="student" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="id" type="xs:ID"/>
              <xs:element name="name" type="xs:string"/>
              <xs:element name="date" type="xs:date"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <!-- Danh sách đăng ký môn học -->
        <xs:element name="enrollment" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="studentRef" type="xs:IDREF" use="required"/>
            <xs:attribute name="course" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>

    <!-- Ràng buộc giá trị id là duy nhất -->
    <xs:unique name="UniqueStudentID">
      <xs:selector xpath="student"/>
      <xs:field xpath="id"/>
    </xs:unique>
  </xs:element>

</xs:schema>

=== mydung1308/CongNgheXML/student_unique.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->



<school xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="student_unique.xsd">
  <student>
    <id>SV01</id>
    <name>Nguyễn Thị Thanh Thúy</name>
    <date>1997-12-20</date>
  </student>
  <student>
    <id>SV02</id>
    <name>Lê Thị Hồng Cẩm</name>
    <date>1998-01-21</date>
  </student>
  <student>
    <id>SV03</id>
    <name>Lê Thị Hồng Cẩm</name>
    <date>1997-11-11</date>
  </student>

  <enrollment studentRef="SV01" course="Toan101"/>
  <enrollment studentRef="SV02" course="Vatly203"/>
  <enrollment studentRef="SV03" course="Hoa305"/>
</school>
